package.json
Test Strategy:
- when I add/install new packages using yarn, flow-typed should update automatically.
=> Add postinstall hook for flow-typed

docs/platforms.txt
This includes 006 also in part. 
https://trello.com/c/aYtNR1x2/10-006-research-requirements-for-various-devices
I will hopefully fill up some missing info on the certain OS-s in the near future.
=> 001 - Test React on devices

package.json, public/index.html, src/components/app/__snapshots__/app.test.js.snap, src/components/app/app.js, yarn.lock
This is a PR for the task https://trello.com/c/T2EdvYj2/17-011-implement-bootstrap
=> 011 - installed react-bootstrap

docs/platforms.md
=> localStorage

src/components/home-container/__snapshots__/home-container.test.js.snap, src/components/home-container/home-container.js, src/components/home-container/home-container.test.js
this PR changes the homeContainer component, it renders all the series now, updated tests
=> change home container to render all series

src/components/app/app.js, src/components/app/app.test.js, src/components/home-container/__snapshots__/home-container.test.js.snap, src/components/home-container/home-container.css, src/components/home-container/home-container.js, src/components/home-container/home-container.test.js, src/components/side-panel/side-panel.js, src/components/side-panel/side-panel.test.js, src/components/slider/__snapshots__/slider.test.js.snap, src/components/slider/parts/__snapshots__/slider-item.test.js.snap, src/components/slider/parts/slider-item.css, src/components/slider/parts/slider-item.js, src/components/slider/parts/slider-item.test.js, src/components/slider/slider.js, src/components/slider/slider.test.js, src/structures/sliderItem.js
=> keyboard navigation

src/components/app/__snapshots__/app-render.test.js.snap, src/components/app/app-render.test.js, src/components/app/app.js, src/components/app/app.test.js
This PR fixes the tests regarding the navigation on homepage.
=> fixing the test for the homepage navigation

src/components/app/app.js, src/components/app/app.test.js, src/components/episode-selected/__snapshots__/episode-selected.test.js.snap, src/components/episode-selected/episode-selected.css, src/components/episode-selected/episode-selected.js, src/components/episode-selected/episode-selected.test.js, src/components/episode-selected/parts/episode-description.css, src/components/home-container/__snapshots__/home-container.test.js.snap, src/components/home-container/home-container.css, src/components/home-container/home-container.js, src/components/home-container/home-container.test.js, src/components/slider/parts/slider-item.css, src/components/slider/slider.css
This PR implements the episode selected component
=> implementing episode selected to homepage

src/colors.css, src/components/video-player-container/parts/video-player-controls.css, src/components/video-player-container/parts/video-player-controls.js, src/components/video-player-container/parts/video-player.css, src/components/video-player-container/parts/video-player.js, src/components/video-player-container/video-player-container.css
You should see full screen video.
=> Video player

src/api/local-storage.js, src/api/local-storage.test.js
I made 2 functions - one for setting and another one for getting progress times of videos using local storage and also added appropriate tests.
=> 038 - localStorage functions

src/components/video-player-container/__snapshots__/video-player-container.test.js.snap, src/components/video-player-container/parts/__snapshots__/video-player-controls.test.js.snap, src/components/video-player-container/parts/video-player-controls.test.js, src/components/video-player-container/parts/video-player.js, src/components/video-player-container/parts/video-player.test.js, src/components/video-player-container/video-player-container.test.js
I did not know to create test when player is null. Other ones should be ok.
=> test for all video Player component

src/components/video-player-container/parts/__snapshots__/video-player-controls.test.js.snap, src/components/video-player-container/parts/video-player-controls.css, src/components/video-player-container/parts/video-player-controls.js, src/components/video-player-container/parts/video-player-controls.test.js, src/components/video-player-container/parts/video-player.js, src/components/video-player-container/parts/video-player.test.js
You should know to navigate in video by keyboards left and right and when you press enter then is executed function for the button.
=> Navigation2

src/components/video-player-container/parts/__snapshots__/video-player-controls.test.js.snap
=> added snapshot for vp controls

src/components/series-detail/__snapshots__/series-container.test.js.snap, src/components/series-detail/series-container.css, src/components/series-detail/series-container.js, src/components/series-detail/series-container.test.js, src/index.js
you souhld see series page when you  visit link /series
=> series detail page

public/assets/Square-Arrow.svg, src/colors.css, src/components/video-player-container/parts/__snapshots__/video-player-controls.test.js.snap, src/components/video-player-container/parts/video-player-controls.css, src/components/video-player-container/parts/video-player-controls.js, src/components/video-player-container/parts/video-player-controls.test.js, src/components/video-player-container/parts/video-player.css, src/components/video-player-container/parts/video-player.js, src/components/video-player-container/parts/video-player.test.js, src/components/video-player-container/video-player-container.js
Do not merge yet. -> tests pending
=> Update video component screen

src/components/series-detail/parts/series-description.css, src/components/series-detail/series-container.js
I fixed navigation bug and added small adjustments in series description (logo width, description text weight)
=> fixed navigation and added small edits in series description page

src/components/app/app.js, src/components/episode-selected/episode-selected.js, src/components/episode-selected/episode-selected.test.js, src/index.js
You should to see episodeID in a url address when you navigate to episode in Home page and you press enter.
=> expanded episode id in url

src/colors.css, src/components/app/app.js, src/components/app/app.test.js, src/components/episode-selected/__snapshots__/episode-selected.test.js.snap, src/components/episode-selected/episode-selected.css, src/components/episode-selected/episode-selected.js, src/components/episode-selected/episode-selected.test.js, src/components/home-container/__snapshots__/home-container.test.js.snap, src/components/home-container/home-container.css, src/components/home-container/home-container.js, src/components/series-detail/__snapshots__/series-container.test.js.snap, src/components/series-detail/parts/__snapshots__/series-description.test.js.snap, src/components/series-detail/parts/series-description.css, src/components/series-detail/parts/series-description.js, src/components/series-detail/series-container.css, src/components/series-detail/series-container.js, src/components/series-detail/series-container.test.js, src/components/side-panel/side-panel.css, src/components/slider/__snapshots__/slider.test.js.snap, src/components/slider/parts/slider-item.css, src/components/slider/slider.js, src/components/slider/slider.test.js, src/components/video-player-container/parts/video-player.js, src/index.css
This PR includes a few things:
1. wheel scrolling
2. bug fixing around navigation
3. UI polishing around series page, sliders, selected state
4. animation around episode popup container.
5. buttons style modification
=> Mixture of things

src/components/slider/__snapshots__/slider.test.js.snap, src/components/slider/slider.js
At last, I changed slider selection behavior. It should work as expected. However, I didn't made tests for it so far. Maybe, I will so during weekend.
=> implemented slider selection behavior

src/components/app/app.js, src/components/app/app.test.js, src/components/episode-selected/__snapshots__/episode-selected.test.js.snap, src/components/episode-selected/episode-selected.js, src/components/episode-selected/episode-selected.test.js, src/components/home-container/home-container.js, src/components/home-container/home-container.test.js, src/components/series-detail/series-container.js
I added functionality for handling arrow down, when episode selected popup is active.
=> added arrow down function from episode selected popup

src/components/app/app.js, src/components/app/app.test.js, src/components/episode-selected/episode-selected.js, src/components/episode-selected/episode-selected.test.js, src/components/side-panel/side-panel.js, src/components/side-panel/side-panel.test.js, src/components/video-player-container/parts/video-player.js, src/components/video-player-container/parts/video-player.test.js
You should to know navigate in webOS tv but just in homePage so far.
=> navigation

src/components/series-detail/series-container.js, src/components/slider/parts/__snapshots__/slider-item.test.js.snap, src/components/slider/parts/slider-item.css, src/components/slider/parts/slider-item.js, src/components/slider/parts/slider-item.test.js, src/components/slider/slider.js
I styled chevron and made function for moving chevron into right position. I added tests too (100% coverage).
=> added chevron for episode selected popup

src/components/episode-selected/episode-selected.css, src/components/episode-selected/episode-selected.js
I applied click events aside from enter events for episode selected component, so that you are able to get to series page or extend and play video.
=> implemented click event for episode selected button and video

src/components/episode-selected/episode-selected.css, src/components/episode-selected/episode-selected.js
Reverts varholak-peter/economist-films#72
=> Revert "implemented click event for episode selected button and video"

package.json, src/components/series-detail/series-container.js, src/components/series-detail/series-container.test.js, src/components/video-player-container/parts/video-player.js, src/components/video-player-container/parts/video-player.test.js, yarn.lock
=> Playlist extravaganza de la muerte

src/components/video-player-container/parts/video-player.js, src/components/video-player-container/parts/video-player.test.js
Changed behaviour of stop button in video component. Usage of stop button should now pause the video.
=> changed Stop button functionality in VP component
